"""Create User and Task tables

Revision ID: 5e426cf8894c
Revises: cf93e2a81d4b
Create Date: 2024-10-30 22:43:44.086955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e426cf8894c'
down_revision: Union[str, None] = 'cf93e2a81d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
